package com.fclark.jqlib.test.models.depot;

/**
 * This class was generated by the JQLib EntityImporter 
 * by Frederick on Sat Apr 02 16:09:57 GMT-04:00 2011
 *
 */
import com.fclark.jqlib.Entity;
import com.fclark.jqlib.column.*;

public class Product extends Entity<Product> {

	public final NUMBER id = new NUMBER("id",this,1);
	public final VARCHAR title = new VARCHAR("title",this);
	public final VARCHAR description = new VARCHAR("description",this);
	public final VARCHAR imageUrl = new VARCHAR("image_url",this);
	public final NUMBER price = new NUMBER("price",this);

	public Product() {
 		 super();
		 this.setName("products");
	}

	public Product(String alias) {
 		 super(alias);
		 this.setName("products");
	}

	 public static Product alias(String alias) {
		 return new Product(alias);
	}
}
