package com.fclark.jqlib.test.models.depot;

/**
 * This class was generated by the JQLib EntityImporter 
 * by Frederick on Sat Apr 02 16:09:57 GMT-04:00 2011
 *
 */
import com.fclark.jqlib.Entity;
import com.fclark.jqlib.column.*;

public class Session extends Entity<Session> {

	public final NUMBER id = new NUMBER("id",this,1);
	public final VARCHAR sessionId = new VARCHAR("session_id",this);
	public final VARCHAR data = new VARCHAR("data",this);
	public final DATE updatedAt = new DATE("updated_at",this);

	public Session() {
 		 super();
		 this.setName("sessions");
	}

	public Session(String alias) {
 		 super(alias);
		 this.setName("sessions");
	}

	 public static Session alias(String alias) {
		 return new Session(alias);
	}
}
